# Generated by Django 6.1 on 2026-09-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_voetbalspeler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voetbalspeler',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
